all:
	gcc -o british_currency british_currency.c 
	gcc -o swap swap.c 
	gcc -o consoleIO consoleIO.c 
submission:
	tar cvzf hw1_jjg.tar.gz commands.txt identifiers.txt british_currency.c swap.c consoleIO.txt
clean:
	rm -f british_currency consoleIO swap hw1_jjg.tar.gz
