all:
	gcc -Wall -o complex complex.c
	gcc -Wall -o fib fibonacci.c
	gcc -Wall -o cipher cipher.c
	gcc -Wall -o tri triangle.c
complex:
	gcc -Wall -o complex complex.c
fib:
	gcc -Wall -o fib fibonacci.c
cipher:
	gcc -Wall -o cipher cipher.c
tri:
	gcc -Wall -o tri triangle.c
clean:
	rm complex fib tri cipher
