all:
	gcc -Wall -o histogram histogram.c
	gcc -Wall -o sieve sieve.c
	gcc -Wall -o sets sets.c
	gcc -Wall -o sort sort.c
debug:
	gcc -Wall -ggdb -o histogram histogram.c
	gcc -Wall -ggdb -o sieve sieve.c
	gcc -Wall -ggdb -o sets sets.c
	gcc -Wall -ggdb -o sort sort.c
clean:
	rm histogram sieve sets sort
